### PR TITLE
Integrate Qt PIMPL idiom into project

### PR DESCRIPTION
**Pull request by mailagentrus**
I think, that project can use PIMPL before export to dll as Qt's plugin... This commit is a "first step" to hide sort/filter magic from headers.

### CODE REVIEW

**Comment by iberiozko** [comment]
Voting for it! Nice done, WTG!

**Comment by mailagentrus** [comment]
Ok, I'll continue to work on this feature!

**Comment by oKcerG** [comment]
Nice contribution, I somehow missed the email notifying me of this PR.
It's quite big so I don't thing I could review it fully before this weekend.

After a quick glance I have some comments though.
First, I'd like to keep the declaration of the base Filter and Sorter classes public (and the helper subclasses like RoleFilter and FilterContainer) so people could potentially implemented their own, their definition could use pimpl if needed, and other classes could be made private.
Second, and this is linked to the first point, I'd prefer if the dummy sorters that I implemented for the test project would stay there, in their `SortFilterProxyModel.Test` import. I don't want them to be released with the library.

I'll need to take more time to review this PR thoroughly.

Thanks a lot for your effort !

**Comment by oKcerG** [comment]
Closing this PR as the repo has diverged too much.

**Pull request closed without merging**
